datafilepath: ../../datafiles/
datafilename: FullDataSet20180726.h5

logging:
    path: ./logs
    filename: Analytics
    #filePath kept for backwards compatibility, but prediction client 1.0.7 > uses two variables (above)
    #filePath: ./diagnostic_logs/PredictionClient/Watchdog
    maxLoggedVerbosity: 7
    maxFileLength: 1048576
    retentionDays: 1
    consoleOutput: True


metrics:
- loadweigh.kg
- bluetooth.devices
- manualcount

periods:
  cddb:
    startdate : 2016-08-01
    enddate : 2017-10-11
  go_live:
    startdate: 2018-05-23
    enddate:

stations:
- VICTRIC
- GTWK
- BRGHTN

weekdays:
- Monday
- Tuesday
- Wednesday
- Thursday
- Friday
- Saturday
- Sunday