datafilepath: ./datafiles/
datafilename: FullDataSet20180720.h5

metrics:
- loadweigh.kg
- bluetooth.devices
- manualcount

periods:
  cddb:
    startdate : 2016-08-01
    enddate : 2017-10-11
  go_live:
    startdate: 2018-05-23
    enddate:




stations:
- VICTRIC
- GTWK
- BRGHTN