datafilepath: ../../datafiles/
datafilename: FullDataSet20180720.h5

data_types:
- loadweigh.kg
- bluetooth.devices
- manualcount

startdate : 2000-01-01 
splitdate : 2018-05-23
enddate : 2050-01-01

stations:
- VICTRIC
- GTWK
- BRGHTN

weekdays:
- Monday
- Tuesday
- Wednesday
- Thursday
- Friday
- Saturday
- Sunday